### PR TITLE
Swapping Forward - Backward

### PR DESCRIPTION
**Pull request by AlexSteiner30**
The robot was moving the opposite way when pressing forward or backward

### CODE REVIEW

**Comment by AlexSteiner30** [comment]
I did that, that's why I created the pull request

**Comment by adeept** [comment]
Usually when these two parameters are modified, the moving direction of the car will change.

Please try again to swap the 0 and 1 in the line of code below.
Dir_forward = 0
Dir_backward = 1


If the moving direction of the trolley does not change, it may be that the modified program has not been saved, or the modified program has not been saved to the correct location.


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  Alex ***@***.***> Date  3/24/2023 03:26 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [adeept/Adeept_RaspTank] Swapping Forward - Backward (PR #34)  

I did that, that's why I created the pull request

**Comment by adeept** [comment]
Robotic arm servo does not work. It may be caused by the following reasons.


1. It may be due to insufficient power supply. Please use a fully charged 18650 battery.
2. It may be that the servo interface is not connected to the correct port. Please confirm whether the circuit connection is correct.
3. The servo or HAT port may be damaged. Please exchange the interface with the servo that can be used normally, and observe the working status of the two servos.


About the direction of robot movement.
It may be caused by incorrect connection of the two motor circuits, or incorrect positive and negative poles of the motor itself.


If you can change the movement direction of the car after modifying the server/move.py file, please let us know the difference between the initial code and the modified code
Initial code:
Dir_forward = 0
Dir_backward = 1
Modified code:
Dir_forward = 1
Dir_backward = 0


After pressing the button on the WEB interface, which directions do not match the theory (please inform the actual direction of movement).
Forward: Y/N
Backward: Y/N
Left: Y/N
Right: Y/N


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  Alex ***@***.***> Date  3/24/2023 20:46 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [adeept/Adeept_RaspTank] Swapping Forward - Backward (PR #34)  

If I change those than left and right mess up to, the robotic arm doesn't work either, my fork works

**Comment by AlexSteiner30** [comment]
I fixed this problems in my fork

**Comment by jtakacs** [comment]
@AlexSteiner30 
I found that the pin variables are not correct.
Let's assume the right motor should be connected to pins A- and A+, the left motor should be connected to B- and B+.
The right motor should rotate clockwise, when driving forward, and the left motor should rotate anticlockwise.
To make this happen, in `move.py`, the pins should be configured this way:
```
Motor_A_EN = 4
Motor_B_EN = 17

Motor_A_Pin1 = 14
Motor_A_Pin2 = 15

Motor_B_Pin1 = 27
Motor_B_Pin2 = 18
```
The rest of the code should work as it is.

**Pull request merged**
